Add 3 new pg-bouncer.ini config options via env variables
bitnami/bitnami-docker-pgbouncer pull request #15
Opened 2021-09-09 13:58 UTC by tybritten

**Description of the change**
Adds the ability to configure `pool_mode`, `max_client_conn`, and `idle_transaction_timeout` via environment variables

**Benefits**
Lets the image create the ini file automatically and still support these extra settings.

**Possible drawbacks**
None

**Applicable issues**
None

**Additional information**

2021-09-09 16:58 UTC, tybritten commented
I added one additional change for a use case we use specifically. If the user wants to use the `*` for all databases on a host, this will now not set the backend db_name.
I also added a `PGBOUNCER_SET_USER` that when set to `True` will add the user to the database entry

2021-09-10 06:50 UTC, juan131 requested changes
Thanks so much for this great contribution @tybritten !!

Please check my comments when you have a chance.

2021-09-10 06:50 UTC, juan131 commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        ini-file set --section "databases" --key "$PGBOUNCER_DATABASE" --value "$DATABASE_VALUE" "$PGBOUNCER_CONF_FILE"
`DATABASE_VALUE` is a local variable (I mean is only used in the `pgbouncer_initialize` function scope), therefore you should treat it like that. Also, use `is_boolean_yes` (an aux. function we have) to deal with `yes/no` and `true/false` env. vars:
```suggestion
        local database_value="host=$POSTGRESQL_HOST port=$POSTGRESQL_PORT"
        if is_boolean_yes "$PGBOUNCER_SET_USER"; then
            database_value+=" user=$POSTGRESQL_USERNAME"
        fi
        if [[ "$PGBOUNCER_DATABASE" != "*" ]]; then
            database_value+=" dbname=$POSTGRESQL_DATABASE"
        fi
        ini-file set --section "databases" --key "$PGBOUNCER_DATABASE" --value "$database_value" "$PGBOUNCER_CONF_FILE"
```

2021-09-10 06:50 UTC, juan131 commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        fi
We should definitely use a loop...
```suggestion
        local -r -a key_value_pairs=(
            "listen_port:${PGBOUNCER_PORT}"
            "listen_addr:${PGBOUNCER_LISTEN_ADDRESS}"
            "auth_file:${PGBOUNCER_AUTH_FILE}"
            "auth_type:${PGBOUNCER_AUTH_TYPE}"
            "pidfile:${PGBOUNCER_PID_FILE}"
            "logfile:${PGBOUNCER_LOG_FILE}"
            "admin_users:${POSTGRESQL_USERNAME}"
            "client_tls_sslmode:${PGBOUNCER_CLIENT_TLS_SSLMODE}"
            "query_wait_timeout:${PGBOUNCER_QUERY_WAIT_TIMEOUT}"
            "unit_socket_dir:${PGBOUNCER_UNIX_SOCKET_DIR}"
            "pool_mode:${PGBOUNCER_POOL_MODE}"
            "max_client_conn:${PGBOUNCER_MAX_CLIENT_CONN}"
            "idle_transaction_timeout:${PGBOUNCER_IDLE_TRANSACTION_TIMEOUT}"
            "default_pool_size:${PGBOUNCER_DEFAULT_POOL_SIZE}"
            "ignore_startup_parameters:${PGBOUNCER_IGNORE_STARTUP_PARAMETERS}"
        )
        for pair in "${key_value_pairs[@]}"; do
            local key="$(awk -F: '{print $1}' <<< "$pair")"
            local value="$(awk -F: '{print $2}' <<< "$pair")"
            if ! is_empty_value "${value}"); then
                ini-file set --section "pgbouncer" --key "${key}" --value "${value}" "$PGBOUNCER_CONF_FILE"
            fi
        done
```

2021-09-10 06:50 UTC, juan131 commented on README.md
> +- `PGBOUNCER_SET_USER`: If you want the above backend PostgreSQL username to be included in the database string, set this to `True`.
This should be a `yes/no` env. variable. `true/false` env. variables are problematic under certain environments.
Also, please indicate the default value.

2021-09-10 10:59 UTC, tybritten commented
Awesome, thanks for the help!

2021-09-14 19:32 UTC, tybritten commented
@juan131 can you give this another look and hopefully merge it?

2021-09-15 06:53 UTC, juan131 reviewed
Awesome! Thanks for implementing the suggestions!

2021-09-15 06:53 UTC, juan131 commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        fi
I have one question: what is the use for avoiding the user information to be excluded from the database string? I mean, I can't think of any situation when including it can be problematic.

2021-09-15 14:53 UTC, tybritten commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        fi
I _think_ that limits the back-end connection to that user, whereas you might want multiple different users connecting to the DB via pg-bouncer. Our use case we want to be able to pin it to a user. I've seen other pg-bouncer configs that exclude it so i figured it was safer to make it optional.

2021-09-16 06:14 UTC, juan131 commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        fi
Understood! Thanks for the details.

2021-09-16 06:15 UTC, juan131 approved these changes
LGTM

2021-09-16 06:27 UTC, juan131 commented
I proceed to send the changes for internal review, once they're accepted I'll merge your PR and trigger a release of the container including your changes.
Thanks again for the contribution!

2021-09-16 13:57 UTC, merged

2021-09-16 13:58 UTC, juan131 commented
Triggering release...

2021-09-16 15:22 UTC, tybritten commented
Awesome. How long will it take to show up on docker hub?

2021-09-17 07:04 UTC, juan131 commented
We found a small issue in the logic (already corrected) and that's why the released was delayed slightly. Minor changes introduce:

- `PGBOUNCER_SET_USER` was renamed to `PGBOUNCER_SET_DATABASE_USER` (suggested in internal review).
- New validations.
- Remove duplicated actions.

The new image is already available (version `1.16.0-r38-debian-10`, please give it a try when possible. Check the commit below:

- https://github.com/bitnami/bitnami-docker-pgbouncer/commit/47eb385dec4369726acbd3eb057e100e42610a5e