Add support for 3 new pgbouncer.ini config options
bitnami/bitnami-docker-pgbouncer pull request #25
Opened 2022-01-04 22:04 UTC by eggshell

**Description of the change**

This will add support to configure `stats_users`, `server_reset_query`, and `server_idle_timeout` parameters with environment variables.

**Benefits**

Extra configuration options available to consumers of this image.

**Possible drawbacks**

None

**Applicable issues**

None

**Additional information**

2022-01-05 08:20 UTC, alemorcuq requested changes
Thanks for the PR! There's an option that takes two different environment variables. I believe it's a typo, so please check that.

2022-01-05 08:20 UTC, alemorcuq commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +            "stats_users:${POSTGRESQL_STATS_USERS}"
Should this be `POSTGRESQL_STATS_USERS` or `PGBOUNCER_STATS_USERS`?

2022-01-05 20:27 UTC, eggshell commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +            "stats_users:${POSTGRESQL_STATS_USERS}"
Thanks for the review! It was indeed a typo, and I changed it to `PGBOUNCER_STATS_USERS` here.

2022-01-07 11:16 UTC, alemorcuq approved these changes

2022-01-07 11:16 UTC, merged