Issue 6 - `ignore_startup_parameters` env var
bitnami/bitnami-docker-pgbouncer pull request #7
Opened 2021-06-20 19:11 UTC by somesocks

- `pgbouncer-env.sh` adding default for PGBOUNCER_IGNORE_STARTUP_PARAMETERS
- `libpgbouncer.sh` setting ignore_startup_parameters to PGBOUNCER_IGNORE_STARTUP_PARAMETERS in auto-generated `pgbouncer.ini`
- adding PGBOUNCER_IGNORE_STARTUP_PARAMETERS to readme

**Description of the change**

Fixes #6.

This PR updates some of the image scripts to add support for a new environment variable PGBOUNCER_IGNORE_STARTUP_PARAMETERS.  This environment variable is used to set `ignore_startup_parameters` in the auto-generated `pgbouncer.ini`.

**Benefits**

As mentioned in the issue, some JDBC connectors can have trouble connecting to pgbouncer because pgbouncer throws an error on unrecognized parameters in startup packets.  The result of this is that some DB tools can't connect to pgbouncer running in the bitnami-docker-pgbouncer image, and there's no easy way to fix it.

By exposing the option to set `ignore_startup_parameters` via environment variable, its easy to fix these connection issues without having to build a customer docker image on top of bitnami-docker-pgbouncer.

**Possible drawbacks**

None.

**Applicable issues**

#6

**Additional information**

You can see screenshots here of "before" and "after" the fix, by running the original and the modified bitnami-docker-pgbouncer running in a minikube cluster on my laptop.

BEFORE:

![Screenshot from 2021-06-20 20-49-32](https://user-images.githubusercontent.com/1326765/122685478-e4cc4e80-d20b-11eb-9014-241665d86c89.png)
![Screenshot from 2021-06-20 20-50-06](https://user-images.githubusercontent.com/1326765/122685482-e9910280-d20b-11eb-807e-133ef8a2487b.png)
![Screenshot from 2021-06-20 20-50-13](https://user-images.githubusercontent.com/1326765/122685484-ed248980-d20b-11eb-821e-fac241b75a63.png)

AFTER:

![Screenshot from 2021-06-20 20-51-47](https://user-images.githubusercontent.com/1326765/122685495-fb72a580-d20b-11eb-9d73-861f8ba4a781.png)
![Screenshot from 2021-06-20 20-51-54](https://user-images.githubusercontent.com/1326765/122685498-fe6d9600-d20b-11eb-889a-ea3d6eebf54e.png)
![Screenshot from 2021-06-20 20-51-58](https://user-images.githubusercontent.com/1326765/122685500-00375980-d20c-11eb-9767-02d1e44d7fe8.png)

2021-06-21 08:05 UTC, javsalgar requested changes
Thank you so much for the PR! Small request

2021-06-21 08:05 UTC, javsalgar commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
I'm missing a default value here. What is the default?

2021-06-21 10:45 UTC, somesocks commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
I think for this property the default is supposed to be empty.  From the `pgbouncer` docs:

![Screenshot from 2021-06-21 12-41-50](https://user-images.githubusercontent.com/1326765/122749882-27cf0600-d28e-11eb-9b3c-3c9bc0f20570.png)

2021-06-22 08:02 UTC, javsalgar commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
Then I'd only set it if it has a value. Could you use the `is_empty_value` bash function?

2021-07-08 06:34 UTC, javsalgar commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
Hi! Did you have time to check this?

2021-07-08 22:26 UTC, somesocks commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
Hi @javsalgar.  Your suggestion makes sense, I just ran out of free time :stuck_out_tongue:.  I'll take a crack at fixing it this weekend.

2021-07-10 11:16 UTC, somesocks commented on 1/debian-10/rootfs/opt/bitnami/scripts/pgbouncer-env.sh
> +export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-}"
@javsalgar pushed a fix to conditionally set `ignore_startup_parameters`, and tested it locally

2021-07-14 08:06 UTC, Dienemy commented
Hello. 
Is there any updates on when these changes would be merged? 
They are handy for my project.

2021-07-14 08:08 UTC, javsalgar reviewed
Small change and we're good to go!

2021-07-14 08:08 UTC, javsalgar commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        if [[ -n "$PGBOUNCER_IGNORE_STARTUP_PARAMETERS" ]]; then
For consistency with other containers, could you change it to this

```suggestion
        if ! is_empty_value "$PGBOUNCER_IGNORE_STARTUP_PARAMETERS"; then
```

2021-07-14 08:18 UTC, Dienemy commented
Hello @javsalgar.

Thanks for the fast reply. 
Looking forward to it be merged.

2021-07-14 09:11 UTC, somesocks commented on 1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh
> +        if [[ -n "$PGBOUNCER_IGNORE_STARTUP_PARAMETERS" ]]; then
Aha, I missed that you were using custom validator functions the first time around,  fixed now

2021-07-15 06:53 UTC, Dienemy commented
Hi @javsalgar @somesocks 
Is there anything else that blocks us from moving forward?

2021-07-16 07:40 UTC, javsalgar approved these changes
We're good to go! Thank you so much!

2021-07-16 07:40 UTC, javsalgar commented
Could you fix the merge issues?

2021-07-16 08:14 UTC, somesocks commented
> Could you fix the merge issues?

@javsalgar  should be good now

2021-07-19 14:34 UTC, merged

2021-07-20 08:25 UTC, Dienemy commented
Thanks a lot, @somesocks @javsalgar

2021-07-26 11:52 UTC, Dienemy commented
Hello, @somesocks  @javsalgar 

Today I had a chance to try this fix, but unfortunately, it looks like it does not work :(

Reviewing the code, I found that "**PGBOUNCER_IGNORE_STARTUP_PARAMETERS**" is passed in the "**pgbouncer_validate**" function instead of "**pgbouncer_initialize**." 
So, according to the lines:

```
    # Clean logs, pids and configuration files from previous restarts
    rm -f "$PGBOUNCER_PID_FILE" "$PGBOUNCER_LOG_FILE" "$PGBOUNCER_AUTH_FILE" "$PGBOUNCER_CONF_FILE"
```

**pgbouncer_initialize** function removes config before initializing.
Could you please take a look? Maybe I missed smth. 
Thanks.

2021-07-26 13:19 UTC, somesocks commented
@javsalgar what happened here?  I'm looking at https://github.com/bitnami/bitnami-docker-pgbouncer/commit/b0e3f5763f4a677998c95f917c8c706d8ff23c7d, and I don't understand why a bot account is committing anything other than debian image bumps.

Even worse, these are obviously bad changes:

![Screenshot from 2021-07-26 15-11-03](https://user-images.githubusercontent.com/1326765/126994237-998eac36-b33c-4f48-adb2-e688bb93cb22.png)
Like @Dienemy said, this has nothing to do with validation, it belongs with the other initialization calls.

![Screenshot from 2021-07-26 15-12-50](https://user-images.githubusercontent.com/1326765/126994482-6457894f-b3fc-4e83-8312-8af0bd74e707.png)
Also, `ignore_startup_parameters` has absolutely nothing to do with TLS, its a pgbouncer connection setting that you can use regardless of whether you're using TLS or not.

2021-07-27 08:08 UTC, javsalgar commented
Hi,

Let me give you some context. The files in this repository are auto-generated by a private, centralized repository in our system (the reason is that we use the same code for other containers in other operating systems, as well as other branches, single vms, etc.). Every time you add a change in one of our container repositories, we migrate this change to our centralized system, which will regenerate the files in this repository (the bitnami-bot account). In this case, I may have messed up with the migration, adding the changes where it shouldn't be. I will work on fixing this

2021-07-28 08:10 UTC, Dienemy commented
Hi @javsalgar. 
Thanks for the clarification. Is there any updates regarding the migration fixes?

2021-07-29 08:03 UTC, javsalgar commented
Now it should be fine

https://github.com/bitnami/bitnami-docker-pgbouncer/commit/de37d204cfb0b89c7f6c0869c66eba61baddd296